Adding german localisation to UTM
utmapp/UTM pull request #3062
Opened 2021-08-28 03:07 UTC by Rastafabisch

I just git cloned UTM, opened it with Xcode to add another language and then edited the files accordingly.

Once done I pushed this to my fork to create this pull request.

While this may sound trivial, this actually is my first one apart from some small web-edits I committed via the web interface, so I really hope this went as desired. At least the changed files do look good.

Best,
Rastafabisch

2021-08-29 21:25 UTC, conath requested changes
Thanks for this localization. It is a good start and there are only minor issues. 
However I noticed the `Localizable.strings` is empty, which would usually be the largest file for localization (IIRC). Will you add it? Otherwise I might pick this PR up and finish the localization myself. Thanks @Rastafabisch !

2021-08-29 21:25 UTC, conath commented on Platform/iOS/de.lproj/InfoPlist.strings
> +"NSMicrophoneUsageDescription" = "Die VM benötigt Mikrofonzugriff.
Is there a new line too much in here?

2021-08-29 21:25 UTC, conath commented on Platform/macOS/de.lproj/InfoPlist.strings
> +"UTM virtual machine" = "UTM Virtuelle Maschinen";
This string describes what the `.utm` file extension is, so it needs to be singular. e. g. "UTM Virtuelle Maschine"

2021-08-29 21:25 UTC, conath commented on UTM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +{
Please remove this file. It's not supposed to be in GIT because Xcode will auto-generate it for you.

2021-08-30 19:55 UTC, Rastafabisch reviewed
I hope I did not mess up the review process, but I think the issues should be resolved. Regarding the `Localizable.strings`, like any other localised file in this commit it was autogenerated by Xcode and then, if it contained any text, translated. Thus it appeared to be empty from the start. However I think `main.strings` file does contain all the translations of the UI.

2021-08-30 19:55 UTC, Rastafabisch commented on Platform/iOS/de.lproj/InfoPlist.strings
> +"NSMicrophoneUsageDescription" = "Die VM benötigt Mikrofonzugriff.
Yes. Fixed!

2021-08-30 21:45 UTC, conath reviewed
I had missed the Main file before, got it. I took the liberty of fixing some typos and some confused terms. Have you tried if this localization works as expected in macOS/iOS? If not just let me know, I can test it.

Edit: I am a little confused by the location of the Main.strings file in the "Legacy" folder. Is this how Xcode generates it?

2021-08-30 22:39 UTC, Rastafabisch commented
Feel free to fix some things. I was not able to test it, because UTM would not compile due to insufficient development permissions. Regarding the Main.strings file Xcode is the culprit indeed.

2022-10-10 20:16 UTC, osy commented
@conath Any update on the status of this? Should it be merged?

2022-10-10 20:43 UTC, conath commented
I will take another look at it, it probably needs to be updated for the new version.

2022-10-19 17:24 UTC, closed without merging