Add virtio-rng-pci device to qemu commandline
utmapp/UTM pull request #3121
Opened 2021-09-20 02:20 UTC by ktprograms

https://wiki.qemu.org/Features/VirtIORNG#Invocation

@conath could you help to test that this doesn't break Windows etc. VMs? You can just add `-device virtio-rng-pci` to the QEMU arguments.

2021-09-20 06:16 UTC, conath commented
What is this for?

2021-09-20 06:49 UTC, ktprograms commented
I have been seeing this in the boot process (the `no randomness supplied` part):
<img width="912" alt="Screenshot 2021-09-20 at 2 45 16 PM" src="https://user-images.githubusercontent.com/71804605/133964900-5518114c-3171-494e-9ead-5d9dbdd1c421.png">

When I saw the QEMU documentation on `virtio-rng-pci` I tried adding it to the QEMU arguments and it worked.
This is what it looks like with adding `-device virtio-rng-pci`:
<img width="912" alt="Screenshot 2021-09-20 at 2 48 54 PM" src="https://user-images.githubusercontent.com/71804605/133965203-c214ef21-d987-4f2f-aecc-8c11d77619e6.png">

2021-09-20 07:03 UTC, conath requested changes
I will test this later on but I already see a compatibility issue: I believe this should only be enabled when EFI boot is enabled because older guests will not be able to interface with this.

2021-09-20 07:07 UTC, ktprograms commented
> older guests will not be able to interface with this

Is it only available for EFI? The `virtio-rng-pci` device just provides a virtio compliant source of randomness (https://wiki.qemu.org/Features/VirtIORNG). The boot messages are just the immediately visible change.

2021-09-20 07:11 UTC, conath commented
What I meant by old guest is ISA only systems or systems that don’t use modern PCI devices. The documentation reads as if it will always add a PCI device. (Maybe it should just be disabled for `pc` system?)

You can leave it like this until I get a chance to test an older system or you can test yourself with a `pc` and `ppc` system. Thanks.

2021-09-26 18:45 UTC, conath requested changes
I tested both the `-device virtio-rng` and `-device virtio-rng-pci` variants and they both cause error on QEMU start with ISA-only systems. So there needs to be a check if the emulated system has a PCI bus.

2021-10-07 23:47 UTC, osy commented
It can be gated by `self.configuration.systemBootUefi`

2021-11-01 04:43 UTC, ktprograms commented
@osy Sorry, this PR wasn't one of my top priorities, but I think it should be good now.

2021-11-01 07:51 UTC, conath approved these changes

2022-01-08 05:17 UTC, merged