Add instruction for tether launching without mac
utmapp/UTM pull request #487
Opened 2020-10-10 09:53 UTC by Assfugil

2020-10-11 06:19 UTC, Assfugil commented
that's about it

2020-10-12 16:30 UTC, demhademha requested changes
You've got a typo, it needs to be libimobiledevice, then the link

2020-10-26 02:43 UTC, Assfugil commented
Is there any problems?

2022-02-13 12:19 UTC, conath commented
Does AltStore on Windows support AltJIT?

2022-02-13 12:45 UTC, closed without merging