Polish localization updates
utmapp/UTM pull request #6164
Opened 2024-02-29 13:11 UTC by mavethee

Adds:
- QEMULauncher string,
- iOS permission strings,
- Remove duplicates (?).

Improves:
- Translation for new features,
- Fix comments and eventual typos.

TODO:
- visionOS strings.

2024-03-02 09:28 UTC, mavethee commented
...aaaaand I have no clue why it fails apperently 🤡

2024-03-03 10:38 UTC, MMP0 requested changes
It looks like you’re manually adding the files, but `.strings` files need to be compiled, so just putting them won’t get them localized.

To link to the Xcode project, you must check `File Inspector` > `Localization` > `Polish` on the right sidebar.
![Sidebar](https://github.com/utmapp/UTM/assets/28616020/d7192634-a313-4e0d-ba4d-0505bb10287e)

If a dialog appears, select “Use file”.
![Dialog](https://github.com/utmapp/UTM/assets/28616020/cc6e177b-c813-40e9-aec2-60445a0e60eb)

Also, in the case of `Info-RemotePlist.strings`, it may cause a conflict with the main branch, so please merge the latest `utmapp:main` branch into your branch first.

2024-03-03 10:38 UTC, MMP0 commented on Platform/pl.lproj/Localizable.strings
> +"Failed to access drive image path." = "Nie udało się uzyskać dostępu do ścieżki obrazu dysku."
Missing semicolon. This line causes the build to fail.
```suggestion
"Failed to access drive image path." = "Nie udało się uzyskać dostępu do ścieżki obrazu dysku.";
```

2024-03-03 10:38 UTC, MMP0 commented on Platform/iOS/pl.lpoj/Info-RemotePlist.strings
It should be `pl.lproj`.

2024-03-03 10:38 UTC, MMP0 commented on Platform/iOS/pl.lpoj/InfoPlist.strings
It should be `pl.lproj`.

2024-03-03 15:38 UTC, mavethee commented
@MMP0 And that's it? I don't use Xcode sooo yeah, so far all strings I wrote were fine displaying fine, but yeah I don't own an iOS device to check or the AVP. After 'using file' on Polish strings, what needs to be done?

2024-03-03 16:16 UTC, mavethee commented
Okay never mind, all it take to upload Xcode file 🤦🏻 
Closing PR was my mistake as wanted to rename branch.
@MMP0 Can you review if you have any more issues to point out?
@osy would it be possible to merge it with stable release as it contains most recent changes in 4.5.x?

2024-03-04 00:41 UTC, MMP0 approved these changes

2024-04-01 03:05 UTC, merged